# Generated by Django 3.2.2 on 2021-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('com_text', models.TextField(verbose_name='Текст комментария')),
            ],
        ),
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Женишбеков К', max_length=100, verbose_name='Автор статьи')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(editable=False, verbose_name='Дата публикации')),
            ],
        ),
    ]
